language: ruby

sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-2
  - ruby-head

install:
  - bundle install --retry=3

env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=master"

matrix:
  include:
    - rvm: jruby-19mode
      gemfile: gemfiles/Gemfile.rails-3.2.x
      env: "JRUBY_OPTS=-Xcext.enabled=true"
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"